version: '3.8'

services:
  dev:
    container_name: nestjs_starter_dev
    image: nestjs-starter-dev:1.0.0
    env_file:
      - ./.env
    environment:
      - NODE_ENV=dev
      - IGNORE_ENV_FILE=false
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 8080:8080
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  prod:
    container_name: nestjs_starter_prod
    image: nestjs-starter-prod:1.0.0
    env_file:
      - ./.env.prod
    environment:
      - NODE_ENV=production
      - IGNORE_ENV_FILE=true
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 8080:8080
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  nesjs-network:
