name: "Release"

on:
  workflow_dispatch:
    inputs:
      newVersion:
        description: "Version to publish: v[MAJOR].[MINOR].[PATCH]"
        required: true
        default: '0.0.0'

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  GITHUB_EMAIL: ${{ secrets.GH_EMAIL }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: "⚙ Set up Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: "✅ Checkout repository"
        uses: actions/checkout@v2

  release:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "💾 Restore Dependencies from cache"
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: "📦 Install packages"
        run: npm install

      - name: "🏷️ Create Release: v${{github.event.inputs.newVersion}}"
        run: |
          git config --global user.name "GitHub CD bot"
          git config --global user.email "${GITHUB_EMAIL}"
          npm run release -- --release-as ${{github.event.inputs.newVersion}}
          git push --follow-tags origin master

      - name: "📄 Create Changelog"
        uses: Bullrich/generate-release-changelog@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}

      - name: "🚀 Publish Release: v${{github.event.inputs.newVersion}}"
        uses: actions/create-release@v1
        with:
          tag_name: "v${{github.event.inputs.newVersion}}"
          release_name: "v${{github.event.inputs.newVersion}}"
          body: |
            ${{ steps.Changelog.outputs.changelog }}

            ---

            > 💬 All notable changes to this project will be documented in [Changelog](${{ github.event.repository.html_url }}/blob/master/CHANGELOG.md) file.
          draft: false
          prerelease: false
